In [1]:
import nlpbbb as bbb
import pprint

In [2]:
settings = {
    "experiment":{
        "lr": [0.0001],
        "epochs": [100],
        "batchsize": [8],
        "val_frequency": [5]
    },
    "model":{
        "brain_biased": [False]
    },
    "misc": {
        "save": [False]
    }
}

In [3]:
#["results/models/05.16.22/model_type:BrainBiasedBert$lr:5e-05/epoch:16/train_info",
#                      "results/models/05.16.22/model_type:BrainBiasedBert$lr:5e-05/epoch:8/train_info"]

In [4]:
base_exps = ["Amazon_BABY", "MNLI_DEFAULT", "SST2_DEFAULT2", "Yelp_ITALIAN"]

In [5]:
#config_dicts = bbb.setup.create_gridsearch(settings, default_name="HarryPotter_DEFAULT", merge_default=True)

In [6]:
run_dicts = []
for be in base_exps:
    config_dicts = bbb.setup.create_gridsearch(settings, default_name=be, merge_default=True)
    for cd in config_dicts:
        run_dicts.append(cd)
    #bbb.setup.run_submitit_job_array(config_dicts, timeout=(12 * 60), mem=16)

config:Amazon_BABY~lr:0.0001~epochs:100~batchsize:8~val_frequency:5~brain_biased:False
config:MNLI_DEFAULT~lr:0.0001~epochs:100~batchsize:8~val_frequency:5~brain_biased:False
config:SST2_DEFAULT2~lr:0.0001~epochs:100~batchsize:8~val_frequency:5~brain_biased:False
config:Yelp_ITALIAN~lr:0.0001~epochs:100~batchsize:8~val_frequency:5~brain_biased:False


In [7]:
#pprint.pprint(run_dicts[0])

In [8]:
bbb.training_loops.run_training_config(run_dicts[3])

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Training Epoch 1/100:   0%|           | 8/8000 [00:00<06:56, 19.20batch/s, train loss (batch)=0.16]

tensor([[0.1764, 0.2140, 0.1663, 0.2627, 0.1806],
        [0.1792, 0.2553, 0.1750, 0.2200, 0.1705],
        [0.1669, 0.2413, 0.1444, 0.2669, 0.1805],
        [0.2319, 0.1938, 0.1468, 0.2562, 0.1713],
        [0.2054, 0.2145, 0.1553, 0.2101, 0.2147],
        [0.1763, 0.2170, 0.1645, 0.2533, 0.1889],
        [0.2023, 0.2388, 0.1309, 0.2442, 0.1837],
        [0.1591, 0.2050, 0.1589, 0.2781, 0.1989]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   0%|         | 16/8000 [00:00<04:40, 28.46batch/s, train loss (batch)=0.139]

tensor([[0.2248, 0.1829, 0.1491, 0.1244, 0.3189],
        [0.2238, 0.1449, 0.1475, 0.1510, 0.3328],
        [0.2272, 0.2134, 0.1478, 0.1104, 0.3012],
        [0.2033, 0.1488, 0.1554, 0.1415, 0.3510],
        [0.2512, 0.1708, 0.1796, 0.1299, 0.2686],
        [0.2742, 0.1512, 0.1482, 0.1342, 0.2922],
        [0.2546, 0.1406, 0.1673, 0.1389, 0.2987],
        [0.2858, 0.1488, 0.1372, 0.1122, 0.3161]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   0%|         | 24/8000 [00:00<04:31, 29.37batch/s, train loss (batch)=0.197]

tensor([[0.1266, 0.1200, 0.0832, 0.0649, 0.6053],
        [0.0860, 0.0939, 0.0799, 0.0653, 0.6749],
        [0.1473, 0.1248, 0.0921, 0.0996, 0.5362],
        [0.0887, 0.1466, 0.0765, 0.0815, 0.6068],
        [0.1126, 0.0827, 0.0736, 0.0602, 0.6710],
        [0.0737, 0.0946, 0.0848, 0.0604, 0.6865],
        [0.1013, 0.1158, 0.0879, 0.0888, 0.6062],
        [0.0981, 0.0963, 0.0747, 0.0541, 0.6769]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   0%|          | 32/8000 [00:01<04:33, 29.10batch/s, train loss (batch)=0.18]

tensor([[0.1633, 0.1344, 0.0918, 0.1138, 0.4967],
        [0.1217, 0.1182, 0.0998, 0.1068, 0.5534],
        [0.1609, 0.1489, 0.0919, 0.1076, 0.4907],
        [0.1017, 0.0790, 0.0748, 0.0857, 0.6589],
        [0.1277, 0.1529, 0.0913, 0.0749, 0.5531],
        [0.1432, 0.1677, 0.0945, 0.0892, 0.5054],
        [0.1502, 0.1258, 0.1055, 0.0977, 0.5207],
        [0.1304, 0.0963, 0.0686, 0.0859, 0.6188]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])
tensor([[0.1943, 0.1699, 0.1216, 0.1721, 0.3420],
        [0.1478, 0.1179, 0.0946, 0.1220, 0.5177],
        [0.1847, 0.1605, 0.1211, 0.1620, 0.3716],
        [0.1610, 0.1307, 0.1072, 0.1461, 0.4549],
        [0.2379, 0.1647, 0.1233, 0.1437, 0.3304],
        [0.1945, 0.1332, 0.0978, 0.1511, 0.4234],
        [0.2336, 0.1885, 0.1216, 0.1538, 0.3025],
        [0.1501, 0.1183, 0.1147, 0.1614, 0.4555]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   1%|         | 48/8000 [00:01<04:34, 28.95batch/s, train loss (batch)=0.148]

tensor([[0.2362, 0.1406, 0.1287, 0.1661, 0.3283],
        [0.1460, 0.1336, 0.1375, 0.1599, 0.4230],
        [0.2023, 0.1542, 0.1301, 0.1534, 0.3600],
        [0.1971, 0.1601, 0.1220, 0.2006, 0.3202],
        [0.1794, 0.1128, 0.1235, 0.1692, 0.4151],
        [0.2153, 0.1361, 0.1075, 0.1623, 0.3790],
        [0.2106, 0.1187, 0.1151, 0.1851, 0.3705],
        [0.2783, 0.1252, 0.1252, 0.1737, 0.2976]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   1%|         | 56/8000 [00:01<04:16, 30.92batch/s, train loss (batch)=0.164]

tensor([[0.1404, 0.1451, 0.1259, 0.1919, 0.3967],
        [0.1945, 0.1137, 0.1517, 0.2424, 0.2977],
        [0.2292, 0.1562, 0.1257, 0.1928, 0.2961],
        [0.2612, 0.1520, 0.1283, 0.2013, 0.2571],
        [0.2190, 0.1707, 0.1239, 0.2032, 0.2832],
        [0.1996, 0.1558, 0.1250, 0.2002, 0.3193],
        [0.1461, 0.1230, 0.1263, 0.1792, 0.4254],
        [0.2294, 0.1562, 0.1342, 0.2056, 0.2746]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   1%|          | 64/8000 [00:02<04:00, 33.02batch/s, train loss (batch)=0.14]

tensor([[0.2076, 0.1556, 0.1440, 0.2294, 0.2633],
        [0.1228, 0.1007, 0.0955, 0.1956, 0.4855],
        [0.1838, 0.1356, 0.1312, 0.2169, 0.3326],
        [0.1775, 0.1346, 0.1346, 0.2276, 0.3258],
        [0.2304, 0.1900, 0.1280, 0.1683, 0.2833],
        [0.2025, 0.1594, 0.1284, 0.2108, 0.2989],
        [0.1654, 0.1252, 0.1309, 0.2249, 0.3536],
        [0.2267, 0.1758, 0.1417, 0.2043, 0.2515]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   1%|         | 72/8000 [00:02<03:44, 35.27batch/s, train loss (batch)=0.151]

tensor([[0.1781, 0.1684, 0.1392, 0.2061, 0.3082],
        [0.1591, 0.1594, 0.1384, 0.2435, 0.2997],
        [0.1696, 0.1539, 0.1480, 0.2693, 0.2593],
        [0.1141, 0.0857, 0.1230, 0.2613, 0.4159],
        [0.1916, 0.1934, 0.1529, 0.2452, 0.2168],
        [0.1492, 0.1528, 0.1325, 0.2591, 0.3064],
        [0.1875, 0.1665, 0.1511, 0.2465, 0.2484],
        [0.1651, 0.1535, 0.1540, 0.2354, 0.2920]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])
tensor([[0.1203, 0.1680, 0.1513, 0.2611, 0.2993],
        [0.1436, 0.1280, 0.1130, 0.2652, 0.3502],
        [0.1850, 0.1346, 0.1632, 0.2432, 0.2740],
        [0.1278, 0.1371, 0.1430, 0.2651, 0.3270],
        [0.1852, 0.2222, 0.1265, 0.3034, 0.1628],
        [0.1308, 0.1733, 0.1208, 0.2968, 0.2783],
        [0.1461, 0.1408, 0.1479, 0.2784, 0.2869],
        [0.0797, 0.0933, 0.1222, 0.2544, 0.4505]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   1%|         | 88/8000 [00:02<04:14, 31.05batch/s, train loss (batch)=0.139]

tensor([[0.1418, 0.1463, 0.1776, 0.3052, 0.2291],
        [0.0864, 0.1042, 0.1237, 0.2643, 0.4214],
        [0.1233, 0.1143, 0.1418, 0.2853, 0.3352],
        [0.1344, 0.1376, 0.1421, 0.2517, 0.3341],
        [0.1151, 0.1519, 0.1548, 0.3081, 0.2701],
        [0.0878, 0.1013, 0.1383, 0.3083, 0.3644],
        [0.0738, 0.0690, 0.1066, 0.2374, 0.5133],
        [0.1444, 0.1600, 0.1528, 0.2815, 0.2612]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])
tensor([[0.1166, 0.1248, 0.1507, 0.2494, 0.3584],
        [0.0808, 0.1452, 0.1336, 0.2071, 0.4333],
        [0.1195, 0.1324, 0.1564, 0.2191, 0.3725],
        [0.1101, 0.1044, 0.1171, 0.2186, 0.4499],
        [0.0781, 0.0837, 0.1214, 0.1946, 0.5222],
        [0.1354, 0.1535, 0.1504, 0.2279, 0.3329],
        [0.1054, 0.1104, 0.1212, 0.2344, 0.4286],
        [0.1027, 0.1113, 0.1441, 0.2199, 0.4219]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   1%|        | 104/8000 [00:03<04:11, 31.42batch/s, train loss (batch)=0.137]

tensor([[0.0553, 0.0538, 0.0896, 0.1232, 0.6781],
        [0.0449, 0.0540, 0.0889, 0.1254, 0.6867],
        [0.1002, 0.0787, 0.1302, 0.1849, 0.5060],
        [0.1145, 0.0854, 0.1407, 0.1689, 0.4906],
        [0.0505, 0.0512, 0.0839, 0.0968, 0.7175],
        [0.0494, 0.0556, 0.0936, 0.1182, 0.6832],
        [0.1379, 0.1532, 0.1454, 0.2179, 0.3457],
        [0.0740, 0.0760, 0.1077, 0.1426, 0.5998]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   1%|        | 112/8000 [00:03<04:27, 29.49batch/s, train loss (batch)=0.157]

tensor([[0.0957, 0.0927, 0.1241, 0.1510, 0.5365],
        [0.1578, 0.1639, 0.1788, 0.1814, 0.3181],
        [0.0735, 0.1007, 0.1314, 0.1375, 0.5570],
        [0.1054, 0.1151, 0.1615, 0.1782, 0.4398],
        [0.0392, 0.0427, 0.0796, 0.0886, 0.7498],
        [0.1554, 0.1230, 0.1345, 0.1323, 0.4548],
        [0.1164, 0.0988, 0.1291, 0.1356, 0.5201],
        [0.0476, 0.0476, 0.0817, 0.0891, 0.7340]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   2%|        | 120/8000 [00:04<04:34, 28.71batch/s, train loss (batch)=0.132]

tensor([[0.0579, 0.0639, 0.1114, 0.0973, 0.6695],
        [0.1299, 0.1190, 0.1607, 0.1240, 0.4664],
        [0.1377, 0.1234, 0.1680, 0.1373, 0.4336],
        [0.1040, 0.1062, 0.1360, 0.1200, 0.5337],
        [0.0406, 0.0499, 0.0921, 0.0685, 0.7489],
        [0.1385, 0.1238, 0.1422, 0.1201, 0.4754],
        [0.0693, 0.0712, 0.1071, 0.0922, 0.6602],
        [0.0841, 0.0569, 0.1248, 0.0926, 0.6416]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   2%|▏       | 128/8000 [00:04<04:31, 29.05batch/s, train loss (batch)=0.163]

tensor([[0.1497, 0.1228, 0.1678, 0.1395, 0.4201],
        [0.0280, 0.0337, 0.0609, 0.0578, 0.8196],
        [0.1097, 0.0907, 0.1382, 0.1181, 0.5434],
        [0.0913, 0.0830, 0.1266, 0.1198, 0.5793],
        [0.1698, 0.1065, 0.1841, 0.1307, 0.4089],
        [0.1442, 0.1325, 0.1573, 0.1703, 0.3956],
        [0.1887, 0.1597, 0.1661, 0.1337, 0.3518],
        [0.1314, 0.1154, 0.1472, 0.1223, 0.4837]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])
tensor([[0.2132, 0.1740, 0.1902, 0.1561, 0.2664],
        [0.1638, 0.1258, 0.1741, 0.1641, 0.3722],
        [0.1977, 0.1048, 0.1721, 0.1462, 0.3791],
        [0.1930, 0.1868, 0.1915, 0.1686, 0.2601],
        [0.1855, 0.1382, 0.1730, 0.1416, 0.3618],
        [0.1574, 0.1171, 0.1781, 0.1369, 0.4105],
        [0.1300, 0.0654, 0.1666, 0.0994, 0.5386],
        [0.0704, 0.0771, 0.1463, 0.1274, 0.5787]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   2%|▏       | 136/8000 [00:04<05:04, 25.79batch/s, train loss (batch)=0.162]

tensor([[0.1097, 0.0861, 0.2027, 0.1727, 0.4289],
        [0.2011, 0.1552, 0.2654, 0.1844, 0.1940],
        [0.1961, 0.1696, 0.2318, 0.1826, 0.2200],
        [0.2096, 0.2059, 0.1731, 0.1571, 0.2543],
        [0.1867, 0.1853, 0.2083, 0.1486, 0.2711],
        [0.1402, 0.1100, 0.1776, 0.1489, 0.4233],
        [0.1964, 0.2226, 0.1706, 0.1662, 0.2442],
        [0.2127, 0.2058, 0.2001, 0.1721, 0.2094]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   2%|▏       | 152/8000 [00:05<04:56, 26.49batch/s, train loss (batch)=0.151]

tensor([[0.2488, 0.2031, 0.2044, 0.1726, 0.1710],
        [0.1531, 0.1209, 0.2024, 0.1717, 0.3519],
        [0.1570, 0.1291, 0.2076, 0.1853, 0.3211],
        [0.1991, 0.2345, 0.1749, 0.1766, 0.2149],
        [0.1752, 0.1184, 0.2622, 0.2210, 0.2233],
        [0.1791, 0.1228, 0.1611, 0.1944, 0.3427],
        [0.2086, 0.1862, 0.1912, 0.2003, 0.2137],
        [0.2251, 0.2024, 0.2113, 0.2174, 0.1438]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   2%|▏       | 160/8000 [00:05<04:31, 28.84batch/s, train loss (batch)=0.156]

tensor([[0.1816, 0.0977, 0.2273, 0.2609, 0.2324],
        [0.2352, 0.2223, 0.1996, 0.1402, 0.2027],
        [0.2022, 0.1844, 0.2156, 0.1921, 0.2057],
        [0.1535, 0.1674, 0.2508, 0.2459, 0.1825],
        [0.2287, 0.1659, 0.1975, 0.1926, 0.2153],
        [0.2160, 0.1902, 0.1910, 0.2214, 0.1814],
        [0.1941, 0.1434, 0.1888, 0.1602, 0.3135],
        [0.1881, 0.1174, 0.1999, 0.1862, 0.3085]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])
tensor([[0.2023, 0.1816, 0.1831, 0.1979, 0.2352],
        [0.1640, 0.1268, 0.1910, 0.2397, 0.2785],
        [0.2621, 0.1833, 0.1806, 0.2130, 0.1610],
        [0.2316, 0.1643, 0.1836, 0.2323, 0.1883],
        [0.2249, 0.1267, 0.2038, 0.2352, 0.2094],
        [0.1845, 0.0920, 0.1646, 0.2723, 0.2866],
        [0.2654, 0.1701, 0.2282, 0.2004, 0.1359],
        [0.0923, 0.0914, 0.2012, 0.2731, 0.3420]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   2%|▏       | 176/8000 [00:06<04:35, 28.36batch/s, train loss (batch)=0.139]

tensor([[0.1453, 0.1557, 0.2231, 0.2640, 0.2119],
        [0.2408, 0.1931, 0.1552, 0.2635, 0.1475],
        [0.1794, 0.1362, 0.1834, 0.2537, 0.2472],
        [0.1404, 0.1544, 0.2452, 0.2670, 0.1929],
        [0.1770, 0.1266, 0.1560, 0.2694, 0.2709],
        [0.1979, 0.1837, 0.1638, 0.2499, 0.2047],
        [0.2289, 0.1664, 0.1858, 0.2440, 0.1750],
        [0.0755, 0.0761, 0.1650, 0.2813, 0.4021]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   2%|▏       | 184/8000 [00:06<04:01, 32.39batch/s, train loss (batch)=0.149]

tensor([[0.0971, 0.0785, 0.1115, 0.2109, 0.5020],
        [0.1740, 0.1228, 0.1519, 0.2847, 0.2666],
        [0.1795, 0.1646, 0.1748, 0.2477, 0.2334],
        [0.1983, 0.1154, 0.1863, 0.3391, 0.1609],
        [0.1698, 0.0964, 0.1590, 0.3187, 0.2561],
        [0.1219, 0.0974, 0.1502, 0.2248, 0.4056],
        [0.1556, 0.1099, 0.1606, 0.2635, 0.3105],
        [0.2269, 0.1545, 0.1541, 0.2407, 0.2238]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


Training Epoch 1/100:   2%|▏       | 184/8000 [00:06<04:40, 27.84batch/s, train loss (batch)=0.149]

tensor([[0.0566, 0.0656, 0.1299, 0.2959, 0.4520],
        [0.1546, 0.1107, 0.1322, 0.3111, 0.2913],
        [0.1350, 0.1075, 0.1531, 0.3864, 0.2179],
        [0.1282, 0.0790, 0.1024, 0.3029, 0.3875],
        [0.1410, 0.1121, 0.1214, 0.3010, 0.3246],
        [0.1782, 0.1438, 0.1364, 0.3133, 0.2283],
        [0.1979, 0.1533, 0.1659, 0.2611, 0.2218],
        [0.1788, 0.0928, 0.1386, 0.2809, 0.3088]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
torch.Size([8, 5])


KeyboardInterrupt: 